import PlayCommand from "./Commands/PlayCommand";
import ClearQueueCommand from "./Commands/ClearQueueCommand";
import DisconnectCommand from "./Commands/DisconnectCommand";
import HelpCommand from "./Commands/HelpCommand";
import MuteCommand from "./Commands/MuteCommand";
import NowPlayingCommand from "./Commands/NowPlayingCommand";
import PauseCommand from "./Commands/PauseCommand";
import QueueCommand from "./Commands/QueueCommand";
import RemoveCommand from "./Commands/RemoveCommand";
import SetVolumeCommand from "./Commands/SetVolumeCommand";
import ResumeCommand from "./Commands/ResumeCommand";
import StopCommand from "./Commands/StopCommand";
import UnmuteCommand from "./Commands/UnmuteCommand";
import Client from "./ActiveConnection/Client";
Client.instance;
new PlayCommand();
new ClearQueueCommand();
new DisconnectCommand();
new HelpCommand();
new MuteCommand();
new NowPlayingCommand();
new PauseCommand();
new QueueCommand();
new RemoveCommand();
new ResumeCommand();
new SetVolumeCommand();
new StopCommand();
new UnmuteCommand();